### ISSUE TITLE
chrome plugin (sometimes) does not work

### ISSUE THREAD

**Issue by raitool** [open-eid/chrome-token-signing#210] opened 2021-11-24 13:39 UTC
In e-Residency, we've had numerous complaints about not being able to log in.
I was able to track down one of the use-cases, where user is EVENTUALLY able to log in.

Windows 10 (clean-install - virtual machine)
Chrome 	96.0.4664.45 (latest)
chrome-token-signing extension - 0.0.32 (latest, installed by latest id-card installer)

https://user-images.githubusercontent.com/8439189/143236174-2d977c74-2108-4e49-9b26-9686a4b897c6.mp4
1. removing certificates - no prior info (recreating "first impression" use-case)
2. some minor html-edit (not required, but I did not want my details leaked)
3. go to page X (Swedbank for example, see "bug scope" for more details)
4. insert card into reader
5. (wait - digidoc client opened on the side to prove that card is correctly inserted)
6. try to log in - fail
7. wait a little more - try to log in - success

Bug scope/level:
* **any page that uses id-card log in** 
   * any service-provider (Swedbank, Telia, e-Residency etc)
   * eesti.ee (replaying the same use-case in eesti.ee and TARA is even worse - sometimes requires browser restart)
* ruined first impression - affects reputation (critical when the concept relies on id-cards, as it does in e-Residency)

-------
web-eid is not an option for us (right now)
* not applicable until web-eid becomes bundled with id-card installation - scope is not a few users (logging in must be possible for any e-resident id-card owner)
* backend is PHP (Laravel) - no examples given

alternative log-in options - work-in-progress (but this is a mitigation, not a solution)
- limiting log in to only e-Residents relied on id-card certificate information (some fields differ for smart-id, mobile-id...e.g. issued by)

**Comment by Counter178** [comment] 2021-11-25 12:51
Thank You for the detailed testing and feedback. 

By checking the video and problem description, the issue is more related to the driver than the signing plugin (Token signing). 

To clarify those two components: 

- Authentication uses [driver components](https://open-eid.github.io/#drivers) to communicate between reader and web browser
- Web Signing process on the other hand uses [web signing components](https://open-eid.github.io/#web-components) like Token Signing 

Since this issue is not related to [Token Signing](https://github.com/open-eid/chrome-token-signing/wiki), I would recommend contacting to main support line [id.ee](https://www.id.ee/artikkel/teavita-meid-probleemist/), where troubleshooting is more sufficient there. 

Closing ticket, since it's not related to Token Signing.

**Closed by Counter178** 2021-11-25 12:51 UTC
